apiVersion: v1
kind: Service
metadata:
  labels:
    app: monodb
  name: mongodb-service
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
